// <auto-generated />
using System;
using CaseGuard.Backend.Assignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaseGuard.Backend.Assignment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260112220812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Invitations_Email");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_Invitations_OrganizationId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Invitations_Status")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "Email", "Status")
                        .HasDatabaseName("IX_Invitations_OrganizationId_Email_Status");

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoRenewalEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AutoRenewalEnabled")
                        .HasDatabaseName("IX_Licenses_AutoRenewalEnabled")
                        .HasFilter("\"AutoRenewalEnabled\" = true AND \"IsActive\" = true");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_Licenses_OrganizationId");

                    b.HasIndex("OrganizationId", "IsActive", "ExpirationDate")
                        .HasDatabaseName("IX_Licenses_OrganizationId_IsActive_ExpirationDate");

                    b.ToTable("Licenses", (string)null);
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.LicenseAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId")
                        .HasDatabaseName("IX_LicenseAssignments_LicenseId");

                    b.HasIndex("OrganizationMemberId")
                        .HasDatabaseName("IX_LicenseAssignments_OrganizationMemberId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LicenseAssignments_UserId");

                    b.HasIndex("LicenseId", "UserId", "OrganizationMemberId")
                        .IsUnique()
                        .HasDatabaseName("IX_LicenseAssignments_LicenseId_UserId_OrganizationMemberId")
                        .HasFilter("\"UnassignedAt\" IS NULL");

                    b.ToTable("LicenseAssignments", (string)null);
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Organizations_Name");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_OrganizationMembers_OrganizationId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_OrganizationMembers_UserId");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganizationMembers_UserId_OrganizationId");

                    b.ToTable("OrganizationMembers", (string)null);
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.Invitation", b =>
                {
                    b.HasOne("CaseGuard.Backend.Assignment.Entities.Organization", "Organization")
                        .WithMany("Invitations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseGuard.Backend.Assignment.Entities.User", "User")
                        .WithMany("Invitations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.License", b =>
                {
                    b.HasOne("CaseGuard.Backend.Assignment.Entities.Organization", "Organization")
                        .WithMany("Licenses")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.LicenseAssignment", b =>
                {
                    b.HasOne("CaseGuard.Backend.Assignment.Entities.License", "License")
                        .WithMany("LicenseAssignments")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseGuard.Backend.Assignment.Entities.OrganizationMember", "OrganizationMember")
                        .WithMany("LicenseAssignments")
                        .HasForeignKey("OrganizationMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseGuard.Backend.Assignment.Entities.User", "User")
                        .WithMany("LicenseAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");

                    b.Navigation("OrganizationMember");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.OrganizationMember", b =>
                {
                    b.HasOne("CaseGuard.Backend.Assignment.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseGuard.Backend.Assignment.Entities.User", "User")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.License", b =>
                {
                    b.Navigation("LicenseAssignments");
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.Organization", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Licenses");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.OrganizationMember", b =>
                {
                    b.Navigation("LicenseAssignments");
                });

            modelBuilder.Entity("CaseGuard.Backend.Assignment.Entities.User", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("LicenseAssignments");

                    b.Navigation("OrganizationMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
